language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rspec"
gemfile:
  - gemfiles/virtus-0_5_x.gemfile
  - gemfiles/virtus-latest.gemfile
  - gemfiles/virtus-edge.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
  - jruby-head
notifications:
  email:
    - manzan@gmail.com
