#!/usr/bin/env ruby

begin
  require "rubygems"
  require "bundler"
rescue LoadError
  raise "Could not load the bundler gem. Install it with `gem install bundler`."
end

begin
  # Set up load paths for all bundled gems
  ENV["BUNDLE_GEMFILE"] = File.expand_path("../../Gemfile", __FILE__)
  Bundler.setup
rescue Bundler::GemNotFound
  raise RuntimeError, "Bundler couldn't find some gems." +
    "Did you run `bundle install`?"
end

require "json-schematized"
require "json"

class Person < JSON::Schematized::Base
  json_schema do
    YAML.load(File.read(File.expand_path("../../spec/fixtures/person.yml", __FILE__)))["person"]
  end
end

class VPerson
  include JSON::Schematized
  json_schema :wrapper => :virtus do
    YAML.load(File.read(File.expand_path("../../spec/fixtures/person.yml", __FILE__)))["person"]
  end
end

require "irb"
IRB.start(__FILE__)
